---
title: "First_Quarto_File.qmd"
author: "Sean Ramos"
format: html
editor: visual
---

# Who would have won the Simon-Ehrlich bet over different decades, and what do long-term prices tell us about resource scarcity?

This article shows how when we use data to test our world views we need accurate tests. This article shows the outcomes of a bet between to researchers. one believes that the world populations will make resources rare and expensive while the other believed that inovations would make the price of materials cheeper. In the end innovation won the day. However there is some debate that the fluctuations were more due to chance. The visuals show the relationship between time and price using the lines on a time series graph.

# How are causes of death registered around the world?

This data looked at how contries around the world record the deaths and calls into question our confidence in the data surrounding deaths. The data is presented with a physical map which does a good job of showing the political boundries while also using the colors to demonstrate the amount of reporting in each country. It is good in the sense That I could look at it with out needing to read much and get the main ideas. However I believe that if they had used barcharts for countries or contenents the the comparisons between countries would have been a lot easier.

# Men are more likely to smoke than women almost everywhere in the world

In this article the researcher was looking at the proprtions of smokers that were women and men. This format was useful because it alowed the data to be fitted as points on a graph for each country. A vertical line was added in that made it clear that any country above it had more men smokers than women smokers. The makers of the graphic chose to color based on continenet and the clustering of dots showed cultural trends in each part of the world. For instance europeans smoked closer to equal amounts why asian countries had the highest gender disparity. Over all the graphic was a gread demonstration of the power of positions and colors to communicate a message. THe only problem is that the data is too clustered and the colors become hard to distinguish.

```{r}
plot(1:20)


```

------------------------------------------------------------------------

# 

# 
